import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/hooks/useCart";
import { Toaster } from "sonner";
import "leaflet/dist/leaflet.css";
import Navbar from "./components/common/Navbar";
import TopBar from "./components/common/Topbar";
import Footer from "./components/footer/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Villa Resort",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CartProvider>
            <TopBar />
            <div className="">
              <Navbar />
            </div>
            {children}
            <Footer />
            <Toaster richColors position="top-right" />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
